CLASS zcl_google_constants DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CONSTANTS google_profile TYPE oa2c_profile VALUE 'Z_GOOGLE_CL_PROFILE' ##NO_TEXT.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_GOOGLE_CONSTANTS IMPLEMENTATION.
ENDCLASS.
